wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
batch_size:
  desc: null
  value: 56
bidirectional:
  desc: null
  value: 'True'
dropout:
  desc: null
  value: 0.16999908764016075
hidden_input_1:
  desc: null
  value: 82
hidden_input_2:
  desc: null
  value: 628
hidden_output:
  desc: null
  value: 694
hidden_size:
  desc: null
  value: 138
learning_rate:
  desc: null
  value: 0.07401758538232829
n_layers:
  desc: null
  value: 4
optimiser:
  desc: null
  value: sgd
patience:
  desc: null
  value: 87
