wandb_version: 1

batch_size:
  value: 47
bidirectional:
  value: 'True'
dropout:
  value: 0.011601353650242396
hidden_input_1:
  value: 923
hidden_input_2:
  value: 1431
hidden_output:
  value: 905
hidden_size:
  value: 921
learning_rate:
  value: 0.005826010885376737
n_layers:
  value: 1
optimiser:
  value: d
pat_drop:
  value: 4.420168484788309
patience:
  value: 75
sched_factor:
  value: 0.10630487960642564
