wandb_version: 1

batch_size:
  value: 2
bidirectional:
  value: 'True'
dropout:
  value: 0.3851934201121196
hidden_input_1:
  value: 670
hidden_input_2:
  value: 585
hidden_output:
  value: 651
hidden_size:
  value: 562
learning_rate:
  value: 0.017812577930016754
n_layers:
  value: 1
optimiser:
  value: d
pat_drop:
  value: 1.703398768698945
patience:
  value: 77
sched_factor:
  value: 0.06080471515083992
