wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
batch_size:
  desc: null
  value: 49
bidirectional:
  desc: null
  value: 'True'
dropout:
  desc: null
  value: 0.06654368092556373
hidden_input_1:
  desc: null
  value: 392
hidden_input_2:
  desc: null
  value: 292
hidden_output:
  desc: null
  value: 515
hidden_size:
  desc: null
  value: 840
learning_rate:
  desc: null
  value: 0.06262882119382882
n_layers:
  desc: null
  value: 3
optimiser:
  desc: null
  value: adam
patience:
  desc: null
  value: 16
