wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.6
batch_size:
  desc: null
  value: 30
bidirectional:
  desc: null
  value: true
dropout:
  desc: null
  value: 0.5
hidden_input_1:
  desc: null
  value: 20
hidden_input_2:
  desc: null
  value: 20
hidden_output:
  desc: null
  value: 20
hidden_size:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.005
n_layers:
  desc: null
  value: 2
optimiser:
  desc: null
  value: adam
patience:
  desc: null
  value: 30
