wandb_version: 1

batch_size:
  value: 56
bidirectional:
  value: 'True'
dropout:
  value: 0.16999908764016075
hidden_input_1:
  value: 82
hidden_input_2:
  value: 628
hidden_output:
  value: 694
hidden_size:
  value: 138
learning_rate:
  value: 0.07401758538232829
n_layers:
  value: 4
optimiser:
  value: sgd
patience:
  value: 87
