wandb_version: 1

batch_size:
  value: 95
bidirectional:
  value: 'True'
dropout:
  value: 0.40149052154387826
hidden_input_1:
  value: 362
hidden_input_2:
  value: 201
hidden_output:
  value: 872
hidden_size:
  value: 211
learning_rate:
  value: 0.08163076905233645
n_layers:
  value: 4
optimiser:
  value: sgd
patience:
  value: 14
