wandb_version: 1

batch_size:
  value: 3
bidirectional:
  value: 'True'
dropout:
  value: 0.22823676920790054
hidden_input_1:
  value: 949
hidden_input_2:
  value: 635
hidden_output:
  value: 980
hidden_size:
  value: 154
learning_rate:
  value: 0.07164097688710941
n_layers:
  value: 4
optimiser:
  value: adam
patience:
  value: 83
