wandb_version: 1

batch_size:
  value: 49
bidirectional:
  value: 'True'
dropout:
  value: 0.06654368092556373
hidden_input_1:
  value: 392
hidden_input_2:
  value: 292
hidden_output:
  value: 515
hidden_size:
  value: 840
learning_rate:
  value: 0.06262882119382882
n_layers:
  value: 3
optimiser:
  value: adam
patience:
  value: 16
