wandb_version: 1

batch_size:
  value: 25
bidirectional:
  value: 'True'
dropout:
  value: 0.38563517471847664
hidden_input_1:
  value: 274
hidden_input_2:
  value: 121
hidden_output:
  value: 355
hidden_size:
  value: 695
learning_rate:
  value: 0.07688131624581515
n_layers:
  value: 1
optimiser:
  value: sgd
patience:
  value: 83
