wandb_version: 1

batch_size:
  value: 51
bidirectional:
  value: 'True'
dropout:
  value: 0.09913945569007387
hidden_input_1:
  value: 566
hidden_input_2:
  value: 983
hidden_output:
  value: 376
hidden_size:
  value: 515
learning_rate:
  value: 0.039076578163633295
n_layers:
  value: 1
optimiser:
  value: adam
patience:
  value: 27
