wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
batch_size:
  desc: null
  value: 51
bidirectional:
  desc: null
  value: 'True'
dropout:
  desc: null
  value: 0.09913945569007387
hidden_input_1:
  desc: null
  value: 566
hidden_input_2:
  desc: null
  value: 983
hidden_output:
  desc: null
  value: 376
hidden_size:
  desc: null
  value: 515
learning_rate:
  desc: null
  value: 0.039076578163633295
n_layers:
  desc: null
  value: 1
optimiser:
  desc: null
  value: adam
patience:
  desc: null
  value: 27
