wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
batch_size:
  desc: null
  value: 3
bidirectional:
  desc: null
  value: 'True'
dropout:
  desc: null
  value: 0.22823676920790054
hidden_input_1:
  desc: null
  value: 949
hidden_input_2:
  desc: null
  value: 635
hidden_output:
  desc: null
  value: 980
hidden_size:
  desc: null
  value: 154
learning_rate:
  desc: null
  value: 0.07164097688710941
n_layers:
  desc: null
  value: 4
optimiser:
  desc: null
  value: adam
patience:
  desc: null
  value: 83
