wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
batch_size:
  desc: null
  value: 47
bidirectional:
  desc: null
  value: 'True'
dropout:
  desc: null
  value: 0.011601353650242396
hidden_input_1:
  desc: null
  value: 923
hidden_input_2:
  desc: null
  value: 1431
hidden_output:
  desc: null
  value: 905
hidden_size:
  desc: null
  value: 921
learning_rate:
  desc: null
  value: 0.005826010885376737
n_layers:
  desc: null
  value: 1
optimiser:
  desc: null
  value: d
pat_drop:
  desc: null
  value: 4.420168484788309
patience:
  desc: null
  value: 75
sched_factor:
  desc: null
  value: 0.10630487960642564
