wandb_version: 1

batch_size:
  value: 53
bidirectional:
  value: 'True'
dropout:
  value: 0.05570501375810466
hidden_input_1:
  value: 851
hidden_input_2:
  value: 452
hidden_output:
  value: 584
hidden_size:
  value: 298
learning_rate:
  value: 0.04859866819632214
n_layers:
  value: 4
pat_drop:
  value: 3.3047290200087422
patience:
  value: 62
sched_factor:
  value: 0.737893519135407
