wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
batch_size:
  desc: null
  value: 64
bidirectional:
  desc: null
  value: 'True'
dropout:
  desc: null
  value: 0.4211876052994846
hidden_input_1:
  desc: null
  value: 884
hidden_input_2:
  desc: null
  value: 303
hidden_output:
  desc: null
  value: 427
hidden_size:
  desc: null
  value: 34
learning_rate:
  desc: null
  value: 0.05238858742263199
n_layers:
  desc: null
  value: 4
optimiser:
  desc: null
  value: d
pat_drop:
  desc: null
  value: 4.131399812388894
patience:
  desc: null
  value: 38
sched_factor:
  desc: null
  value: 0.5952939738620511
