wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
batch_size:
  desc: null
  value: 25
bidirectional:
  desc: null
  value: 'True'
dropout:
  desc: null
  value: 0.38563517471847664
hidden_input_1:
  desc: null
  value: 274
hidden_input_2:
  desc: null
  value: 121
hidden_output:
  desc: null
  value: 355
hidden_size:
  desc: null
  value: 695
learning_rate:
  desc: null
  value: 0.07688131624581515
n_layers:
  desc: null
  value: 1
optimiser:
  desc: null
  value: sgd
patience:
  desc: null
  value: 83
